repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: check-merge-conflict
  - id: check-case-conflict
  - id: trailing-whitespace
  - id: end-of-file-fixer
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.89.1
  hooks:
  - id: terraform_fmt
  - id: terraform_validate
  - id: terraform_checkov
  - id: terraform_tflint
    exclude: '/tests/.*$'
    args:
    - '--args=--config=__GIT_WORKING_DIR__/.tflint.hcl'
